### ISSUE TITLE
Youtube is a blank page.

### ISSUE THREAD

**Issue by zappathustra** [luakit/luakit#636]
After Wikipedia, it's YouTube that's acting weirdly now: nothing loads, except the logo:

![youtube](https://user-images.githubusercontent.com/1642300/34339206-e213abca-e970-11e7-94ff-1d033cdc8cee.png)

The menu icon isn't clickable. The source seems pretty normal, so I guess it's a rendering issue.

If I go to a video through an external link, the video loads, but that's all:

![youtube2](https://user-images.githubusercontent.com/1642300/34339218-54941dba-e971-11e7-982f-67fbba0a1bf0.png)

Other webkit browsers (Midori, at least) display the page properly.

**Comment by JR1994** [comment]
I just tested and YouTube loads fine for me.

**Comment by aidanholm** [comment]
Have you set a custom useragent for youtube? I've seen it cause those symptoms

**Comment by zappathustra** [comment]
Indeed, with the useragent back to default, everything is ok. Sorry I didn't make the connection!

**Comment by aidanholm** [comment]
No problem! It's a race condition, really: the user agent is changed when the load status changes to provisional (or redirected), but the actual network request is made from a separate thread. To properly fix this, user agents would have to be set from a `send-request` hook in `webview_wm.lua`

**Comment by zappathustra** [comment]
For the record, I didn't change the UA only for YouTube, it's a global setting in my rc file.

I did that for one website that warns me with "Your browser is not blah blah, click here if you wish to continue anyway", which is quite annoying.

Anyway, it made me realize that I change settings with:

`settings.<option> = <value>`

instead of

`settings.set_setting(<option>, <value>)`

Is there anything wrong with that, except that you can't set per domain? (Sorry if that's not the place to ask!)

**Comment by aidanholm** [comment]
Hm; ok that might be a separate bug then, if it's not a domain-specific rule.

That's the API you're supposed to use. The `set_setting()` function is for modules to use and has different behavior; this should probably be better-documented.

You can do `settings.on["example.com"].foo.bar` to set per-domain settings

**Comment by akegalj** [comment]
I am very new to luakit. Can somebody give me pointers how this can be fixed ?

**Comment by aidanholm** [comment]
@akegalj Hi and welcome!

This issue is caused by having set a custom user agent: either in your rc.lua file, or from the luakit://settings/ page. In luakit://settings/, if the input box for `webview.user_agent` is empty, it will use the default, which should fix the issue. If the `webview.user_agent` setting is greyed out and the inputbox cannot be edited, that means you've customized `webview.user_agent` in your rc.lua file.

Hope that helps! Feel free to ask if you have questions

**Comment by akegalj** [comment]
@aidanholm hey :)

Hm, then thats strange because `user_agent` is empty and editable. Also nothing is set up in console (see pic)

![look](https://user-images.githubusercontent.com/2461951/34425404-cf3cf692-ec2b-11e7-9167-f6fff2ff988f.png)

Also, seems like `rc.lua` doesn't have custom setting nither:
```
[akegalj@notebook ~]$ grep agent /etc/xdg/luakit/rc.lua 
[akegalj@notebook ~]$ echo $?
1
```

Am I doing something wrong?

**Comment by aidanholm** [comment]
If you use the default config (`luakit -c /etc/xdg/luakit/rc.lua`) does the problem persist?
What's the output of this command? `:lua w:notify(luakit.version.." / "..luakit.webkit_version)`

**Comment by akegalj** [comment]
version:
![look](https://user-images.githubusercontent.com/2461951/34438829-c3a5fc92-eca9-11e7-8e73-59bff45de0e7.png)

yes, problem persist. Looks like I am using version that is ahead of released version (by commit hash?) - maybe there is some regression in my version. I can downgrade and compile  lower version to fix it.


This is not blocker to me though as I can follow instructoins and workaround proposed here https://bbs.archlinux.org/viewtopic.php?id=197393

**Comment by aidanholm** [comment]
That's a very recent version, but it shouldn't be causing this problem.

**Comment by c0dev0id** [comment]
This can be reproduced every once in a while. The problem is mainly that youtube programs based on the user agend. The solution is to set the user_agent to something that youtube (and other sites) understand.

I'm currently using `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36`.

**Comment by c0dev0id** [comment]
So, from what I read, the solution can be
- disable HW acceleration
- wait for the webkit bug to be fixed (https://bugs.webkit.org/show_bug.cgi?id=197141)

I think you could also try `export LIBGL_DRI3_DISABLE=1` before starting luakit, which sometimes helps with video issues.

Either way, there is not really anything we can do here from the luakit end, right? Therefore I'm closing the issue here. Feel free to reopen it if you think otherwise.
